backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "public/assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "blog"
    label: "博客文章"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "分类", name: "categories", widget: "string"}
      - {label: "标签", name: "tags", widget: "list", field: {label: "标签", name: "tag", widget: "string"}}
      - {label: "文章ID", name: "id", widget: "string"}
      - {label: "创建日期", name: "date", widget: "datetime"}
      - {label: "更新日期", name: "updated", widget: "datetime", required: false}
      - {label: "封面图", name: "cover", widget: "string", required: false}
      - {label: "是否推荐", name: "recommend", widget: "boolean", default: false}
      - {label: "是否置顶", name: "top", widget: "boolean", default: false}
      - {label: "是否隐藏", name: "hide", widget: "boolean", default: false}
      - {label: "内容", name: "body", widget: "markdown"}

  - name: "config"
    label: "网站配置"
    files:
      - file: "src/config.ts"
        label: "网站设置"
        name: "config"
        fields:
          - {label: "网站标题", name: "Title", widget: "string"}
          - {label: "网站地址", name: "Site", widget: "string"}
          - {label: "副标题", name: "Subtitle", widget: "string"}
          - {label: "网站描述", name: "Description", widget: "text"}
          - {label: "作者", name: "Author", widget: "string"}
          - {label: "作者头像", name: "Avatar", widget: "string"}
          - {label: "座右铭", name: "Motto", widget: "string"}
          - {label: "网站缩略图", name: "Cover", widget: "string"}
          - {label: "侧边栏公告", name: "Tips", widget: "text", required: false}
          - {label: "打字机文案", name: "TypeWriteList", widget: "list", field: {label: "文案", name: "text", widget: "string"}}
          - {label: "网站创建时间", name: "CreateTime", widget: "string"}
          - {label: "页面阻尼滚动速度", name: "ScrollSpeed", widget: "number"}
          - {label: "博客音乐组件解析接口", name: "vhMusicApi", widget: "string"}
          - label: "Banner配置"
            name: "HomeBanner"
            widget: "object"
            fields:
              - {label: "启用Banner", name: "enable", widget: "boolean"}
              - {label: "首页高度", name: "HomeHeight", widget: "string"}
              - {label: "其他页面高度", name: "PageHeight", widget: "string"}
              - {label: "背景", name: "background", widget: "string"}
          - label: "主题颜色"
            name: "Theme"
            widget: "object"
            fields:
              - {label: "主题颜色", name: "--vh-main-color", widget: "string"}
              - {label: "字体颜色", name: "--vh-font-color", widget: "string"}
              - {label: "侧边栏宽度", name: "--vh-aside-width", widget: "string"}
              - {label: "全局圆角", name: "--vh-main-radius", widget: "string"}
              - {label: "主体内容宽度", name: "--vh-main-max-width", widget: "string"}
          - label: "导航栏配置"
            name: "Navs"
            widget: "list"
            fields:
              - {label: "文本", name: "text", widget: "string"}
              - {label: "链接", name: "link", widget: "string"}
              - {label: "图标", name: "icon", widget: "string"}
              - {label: "新窗口打开", name: "target", widget: "boolean", required: false}
          - label: "侧边栏网站"
            name: "WebSites"
            widget: "list"
            fields:
              - {label: "文本", name: "text", widget: "string"}
              - {label: "链接", name: "link", widget: "string"}
              - {label: "图标", name: "icon", widget: "string"}
          - label: "侧边栏展示"
            name: "AsideShow"
            widget: "object"
            fields:
              - {label: "展示个人网站", name: "WebSitesShow", widget: "boolean"}
              - {label: "展示分类", name: "CategoriesShow", widget: "boolean"}
              - {label: "展示标签", name: "TagsShow", widget: "boolean"}
              - {label: "展示推荐文章", name: "recommendArticleShow", widget: "boolean"}
          - {label: "DNS预解析地址", name: "DNSOptimization", widget: "list", field: {label: "地址", name: "url", widget: "string"}}

  - name: "links"
    label: "友情链接"
    files:
      - file: "src/page_data/Link.ts"
        label: "友情链接配置"
        name: "links"
        fields:
          - {label: "API 接口", name: "api", widget: "string", required: false}
          - {label: "链接数据", name: "data", widget: "list", fields: [
              {label: "名称", name: "name", widget: "string"},
              {label: "链接", name: "link", widget: "string"},
              {label: "头像", name: "avatar", widget: "string"},
              {label: "描述", name: "descr", widget: "string"}
            ]}

  - name: "talking"
    label: "动态说说"
    files:
      - file: "src/page_data/Talking.ts"
        label: "动态配置"
        name: "talking"
        fields:
          - {label: "API 接口", name: "api", widget: "string", required: false}
          - {label: "动态数据", name: "data", widget: "list", fields: [
              {label: "日期", name: "date", widget: "datetime"},
              {label: "标签", name: "tags", widget: "list", field: {label: "标签", name: "tag", widget: "string"}},
              {label: "内容", name: "content", widget: "text"}
            ]}
