backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/assets/uploads" # Media files will be stored in the repo under static/uploads
public_folder: "/assets/uploads" # The src attribute for uploaded media will begin with /uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "博客文章" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "publishDate", widget: "datetime"}
      - {label: "作者", name: "author", widget: "string", default: "虎"}
      - {label: "标签", name: "tags", widget: "list", default: ["未分类"]}
      - {label: "封面图片", name: "cover", widget: "image", required: false}
      - {label: "摘要", name: "description", widget: "text", required: false}
      - {label: "正文", name: "body", widget: "markdown"}